// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pkg/proto/client.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Clients authorization for accessing master
type ClientAuthorization struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ClientAuthorization) Reset() {
	*x = ClientAuthorization{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthorization) ProtoMessage() {}

func (x *ClientAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthorization.ProtoReflect.Descriptor instead.
func (*ClientAuthorization) Descriptor() ([]byte, []int) {
	return file_pkg_proto_client_proto_rawDescGZIP(), []int{0}
}

func (x *ClientAuthorization) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientAuthorization) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// True or false if authorization is ok
type ClientAuthorizationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *ClientAuthorizationResult) Reset() {
	*x = ClientAuthorizationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientAuthorizationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthorizationResult) ProtoMessage() {}

func (x *ClientAuthorizationResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthorizationResult.ProtoReflect.Descriptor instead.
func (*ClientAuthorizationResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_client_proto_rawDescGZIP(), []int{1}
}

func (x *ClientAuthorizationResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// The request which user has
type ClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*ClientRequest_NewJob
	//	*ClientRequest_JobList
	//	*ClientRequest_JobLog
	//	*ClientRequest_NodeList
	//	*ClientRequest_NodeTop
	Request isClientRequest_Request `protobuf_oneof:"request"`
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_client_proto_rawDescGZIP(), []int{2}
}

func (m *ClientRequest) GetRequest() isClientRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *ClientRequest) GetNewJob() *ClientNewJobMessage {
	if x, ok := x.GetRequest().(*ClientRequest_NewJob); ok {
		return x.NewJob
	}
	return nil
}

func (x *ClientRequest) GetJobList() *emptypb.Empty {
	if x, ok := x.GetRequest().(*ClientRequest_JobList); ok {
		return x.JobList
	}
	return nil
}

func (x *ClientRequest) GetJobLog() *GetJobLogsRequest {
	if x, ok := x.GetRequest().(*ClientRequest_JobLog); ok {
		return x.JobLog
	}
	return nil
}

func (x *ClientRequest) GetNodeList() *emptypb.Empty {
	if x, ok := x.GetRequest().(*ClientRequest_NodeList); ok {
		return x.NodeList
	}
	return nil
}

func (x *ClientRequest) GetNodeTop() *emptypb.Empty {
	if x, ok := x.GetRequest().(*ClientRequest_NodeTop); ok {
		return x.NodeTop
	}
	return nil
}

type isClientRequest_Request interface {
	isClientRequest_Request()
}

type ClientRequest_NewJob struct {
	NewJob *ClientNewJobMessage `protobuf:"bytes,1,opt,name=newJob,proto3,oneof"`
}

type ClientRequest_JobList struct {
	JobList *emptypb.Empty `protobuf:"bytes,2,opt,name=jobList,proto3,oneof"`
}

type ClientRequest_JobLog struct {
	JobLog *GetJobLogsRequest `protobuf:"bytes,3,opt,name=jobLog,proto3,oneof"`
}

type ClientRequest_NodeList struct {
	NodeList *emptypb.Empty `protobuf:"bytes,4,opt,name=nodeList,proto3,oneof"`
}

type ClientRequest_NodeTop struct {
	NodeTop *emptypb.Empty `protobuf:"bytes,5,opt,name=nodeTop,proto3,oneof"`
}

func (*ClientRequest_NewJob) isClientRequest_Request() {}

func (*ClientRequest_JobList) isClientRequest_Request() {}

func (*ClientRequest_JobLog) isClientRequest_Request() {}

func (*ClientRequest_NodeList) isClientRequest_Request() {}

func (*ClientRequest_NodeTop) isClientRequest_Request() {}

// Status of a slave to send to client with node list
type SlaveStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Dead    bool   `protobuf:"varint,3,opt,name=dead,proto3" json:"dead,omitempty"`
}

func (x *SlaveStatus) Reset() {
	*x = SlaveStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlaveStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveStatus) ProtoMessage() {}

func (x *SlaveStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveStatus.ProtoReflect.Descriptor instead.
func (*SlaveStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_client_proto_rawDescGZIP(), []int{3}
}

func (x *SlaveStatus) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SlaveStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SlaveStatus) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

// An array of SlaveStatus
type SlavesStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status []*SlaveStatus `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
}

func (x *SlavesStatus) Reset() {
	*x = SlavesStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlavesStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlavesStatus) ProtoMessage() {}

func (x *SlavesStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlavesStatus.ProtoReflect.Descriptor instead.
func (*SlavesStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_client_proto_rawDescGZIP(), []int{4}
}

func (x *SlavesStatus) GetStatus() []*SlaveStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Result of top command on slaves
type SlavesTop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Both slave_ids and slave_tops must have the same size.
	// Same index in slave_id must be for same index in slave_top.
	SlaveIds  []uint32    `protobuf:"varint,1,rep,packed,name=slave_ids,json=slaveIds,proto3" json:"slave_ids,omitempty"`
	SlaveTops []*SlaveTop `protobuf:"bytes,2,rep,name=slave_tops,json=slaveTops,proto3" json:"slave_tops,omitempty"`
}

func (x *SlavesTop) Reset() {
	*x = SlavesTop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlavesTop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlavesTop) ProtoMessage() {}

func (x *SlavesTop) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlavesTop.ProtoReflect.Descriptor instead.
func (*SlavesTop) Descriptor() ([]byte, []int) {
	return file_pkg_proto_client_proto_rawDescGZIP(), []int{5}
}

func (x *SlavesTop) GetSlaveIds() []uint32 {
	if x != nil {
		return x.SlaveIds
	}
	return nil
}

func (x *SlavesTop) GetSlaveTops() []*SlaveTop {
	if x != nil {
		return x.SlaveTops
	}
	return nil
}

// JobData is the struct which we sent into JobsList
type JobData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The command of this job
	Cmd string `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	// Which node ran or is running this job.
	// If the job hasn't been started, this is zero.
	NodeId uint32 `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Types that are assignable to Status:
	//
	//	*JobData_Pending
	//	*JobData_Running
	//	*JobData_ExitCode
	//	*JobData_RunError
	Status isJobData_Status `protobuf_oneof:"status"`
}

func (x *JobData) Reset() {
	*x = JobData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_client_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobData) ProtoMessage() {}

func (x *JobData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_client_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobData.ProtoReflect.Descriptor instead.
func (*JobData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_client_proto_rawDescGZIP(), []int{6}
}

func (x *JobData) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *JobData) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *JobData) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (m *JobData) GetStatus() isJobData_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (x *JobData) GetPending() *emptypb.Empty {
	if x, ok := x.GetStatus().(*JobData_Pending); ok {
		return x.Pending
	}
	return nil
}

func (x *JobData) GetRunning() *emptypb.Empty {
	if x, ok := x.GetStatus().(*JobData_Running); ok {
		return x.Running
	}
	return nil
}

func (x *JobData) GetExitCode() int32 {
	if x, ok := x.GetStatus().(*JobData_ExitCode); ok {
		return x.ExitCode
	}
	return 0
}

func (x *JobData) GetRunError() string {
	if x, ok := x.GetStatus().(*JobData_RunError); ok {
		return x.RunError
	}
	return ""
}

type isJobData_Status interface {
	isJobData_Status()
}

type JobData_Pending struct {
	// Job is waiting for a slave to become free
	Pending *emptypb.Empty `protobuf:"bytes,4,opt,name=pending,proto3,oneof"`
}

type JobData_Running struct {
	// Job is running inside node
	Running *emptypb.Empty `protobuf:"bytes,5,opt,name=running,proto3,oneof"`
}

type JobData_ExitCode struct {
	// Job has been exited with given exit code
	ExitCode int32 `protobuf:"zigzag32,6,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

type JobData_RunError struct {
	// We couldn't run the job for following reason
	RunError string `protobuf:"bytes,7,opt,name=run_error,json=runError,proto3,oneof"`
}

func (*JobData_Pending) isJobData_Status() {}

func (*JobData_Running) isJobData_Status() {}

func (*JobData_ExitCode) isJobData_Status() {}

func (*JobData_RunError) isJobData_Status() {}

// List of all jobs which master has
type JobList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jobs []*JobData `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
}

func (x *JobList) Reset() {
	*x = JobList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_client_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobList) ProtoMessage() {}

func (x *JobList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_client_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobList.ProtoReflect.Descriptor instead.
func (*JobList) Descriptor() ([]byte, []int) {
	return file_pkg_proto_client_proto_rawDescGZIP(), []int{7}
}

func (x *JobList) GetJobs() []*JobData {
	if x != nil {
		return x.Jobs
	}
	return nil
}

// A job to send to a slave
type ClientNewJobMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// If set, the job contains a payload
	PayloadName *string `protobuf:"bytes,1,opt,name=payload_name,json=payloadName,proto3,oneof" json:"payload_name,omitempty"`
}

func (x *ClientNewJobMessage) Reset() {
	*x = ClientNewJobMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_client_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientNewJobMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientNewJobMessage) ProtoMessage() {}

func (x *ClientNewJobMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_client_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientNewJobMessage.ProtoReflect.Descriptor instead.
func (*ClientNewJobMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_client_proto_rawDescGZIP(), []int{8}
}

func (x *ClientNewJobMessage) GetPayloadName() string {
	if x != nil && x.PayloadName != nil {
		return *x.PayloadName
	}
	return ""
}

// ClientJobSentResult is the result of a new job request.
// It can either fail or succeed.
type ClientJobSentResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*ClientJobSentResult_JobId
	//	*ClientJobSentResult_Error
	Result isClientJobSentResult_Result `protobuf_oneof:"result"`
}

func (x *ClientJobSentResult) Reset() {
	*x = ClientJobSentResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_client_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientJobSentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientJobSentResult) ProtoMessage() {}

func (x *ClientJobSentResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_client_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientJobSentResult.ProtoReflect.Descriptor instead.
func (*ClientJobSentResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_client_proto_rawDescGZIP(), []int{9}
}

func (m *ClientJobSentResult) GetResult() isClientJobSentResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *ClientJobSentResult) GetJobId() *UUID {
	if x, ok := x.GetResult().(*ClientJobSentResult_JobId); ok {
		return x.JobId
	}
	return nil
}

func (x *ClientJobSentResult) GetError() string {
	if x, ok := x.GetResult().(*ClientJobSentResult_Error); ok {
		return x.Error
	}
	return ""
}

type isClientJobSentResult_Result interface {
	isClientJobSentResult_Result()
}

type ClientJobSentResult_JobId struct {
	JobId *UUID `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3,oneof"`
}

type ClientJobSentResult_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ClientJobSentResult_JobId) isClientJobSentResult_Result() {}

func (*ClientJobSentResult_Error) isClientJobSentResult_Result() {}

var File_pkg_proto_client_proto protoreflect.FileDescriptor

var file_pkg_proto_client_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x13, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x2b, 0x0a, 0x19, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x22, 0xa2, 0x02, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x34, 0x0a, 0x06, 0x6e, 0x65, 0x77, 0x4a, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4e, 0x65, 0x77, 0x4a, 0x6f, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x06, 0x6e, 0x65, 0x77, 0x4a, 0x6f, 0x62, 0x12, 0x32, 0x0a, 0x07, 0x6a, 0x6f, 0x62, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x48, 0x00, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x06,
	0x6a, 0x6f, 0x62, 0x4c, 0x6f, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x4c, 0x6f, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6a, 0x6f, 0x62, 0x4c, 0x6f, 0x67,
	0x12, 0x34, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x6f,
	0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x54, 0x6f,
	0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48,
	0x00, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x70, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x0b, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x65,
	0x61, 0x64, 0x22, 0x3a, 0x0a, 0x0c, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6c, 0x61, 0x76, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x58,
	0x0a, 0x09, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x73, 0x54, 0x6f, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x6c, 0x61, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08,
	0x73, 0x6c, 0x61, 0x76, 0x65, 0x49, 0x64, 0x73, 0x12, 0x2e, 0x0a, 0x0a, 0x73, 0x6c, 0x61, 0x76,
	0x65, 0x5f, 0x74, 0x6f, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x54, 0x6f, 0x70, 0x52, 0x09, 0x73,
	0x6c, 0x61, 0x76, 0x65, 0x54, 0x6f, 0x70, 0x73, 0x22, 0x81, 0x02, 0x0a, 0x07, 0x4a, 0x6f, 0x62,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x63, 0x6d, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x07,
	0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x12, 0x32, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x07, 0x72, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x11, 0x48, 0x00, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x72, 0x75, 0x6e, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x72, 0x75, 0x6e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2d, 0x0a, 0x07,
	0x4a, 0x6f, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x6f,
	0x62, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x22, 0x4e, 0x0a, 0x13, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x65, 0x77, 0x4a, 0x6f, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x26, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5d, 0x0a, 0x13, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x48,
	0x00, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x0f, 0x5a, 0x0d, 0x57, 0x4c,
	0x46, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_client_proto_rawDescOnce sync.Once
	file_pkg_proto_client_proto_rawDescData = file_pkg_proto_client_proto_rawDesc
)

func file_pkg_proto_client_proto_rawDescGZIP() []byte {
	file_pkg_proto_client_proto_rawDescOnce.Do(func() {
		file_pkg_proto_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_client_proto_rawDescData)
	})
	return file_pkg_proto_client_proto_rawDescData
}

var file_pkg_proto_client_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_proto_client_proto_goTypes = []interface{}{
	(*ClientAuthorization)(nil),       // 0: proto.ClientAuthorization
	(*ClientAuthorizationResult)(nil), // 1: proto.ClientAuthorizationResult
	(*ClientRequest)(nil),             // 2: proto.ClientRequest
	(*SlaveStatus)(nil),               // 3: proto.SlaveStatus
	(*SlavesStatus)(nil),              // 4: proto.SlavesStatus
	(*SlavesTop)(nil),                 // 5: proto.SlavesTop
	(*JobData)(nil),                   // 6: proto.JobData
	(*JobList)(nil),                   // 7: proto.JobList
	(*ClientNewJobMessage)(nil),       // 8: proto.ClientNewJobMessage
	(*ClientJobSentResult)(nil),       // 9: proto.ClientJobSentResult
	(*emptypb.Empty)(nil),             // 10: google.protobuf.Empty
	(*GetJobLogsRequest)(nil),         // 11: proto.GetJobLogsRequest
	(*SlaveTop)(nil),                  // 12: proto.SlaveTop
	(*UUID)(nil),                      // 13: proto.UUID
}
var file_pkg_proto_client_proto_depIdxs = []int32{
	8,  // 0: proto.ClientRequest.newJob:type_name -> proto.ClientNewJobMessage
	10, // 1: proto.ClientRequest.jobList:type_name -> google.protobuf.Empty
	11, // 2: proto.ClientRequest.jobLog:type_name -> proto.GetJobLogsRequest
	10, // 3: proto.ClientRequest.nodeList:type_name -> google.protobuf.Empty
	10, // 4: proto.ClientRequest.nodeTop:type_name -> google.protobuf.Empty
	3,  // 5: proto.SlavesStatus.status:type_name -> proto.SlaveStatus
	12, // 6: proto.SlavesTop.slave_tops:type_name -> proto.SlaveTop
	13, // 7: proto.JobData.id:type_name -> proto.UUID
	10, // 8: proto.JobData.pending:type_name -> google.protobuf.Empty
	10, // 9: proto.JobData.running:type_name -> google.protobuf.Empty
	6,  // 10: proto.JobList.jobs:type_name -> proto.JobData
	13, // 11: proto.ClientJobSentResult.job_id:type_name -> proto.UUID
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pkg_proto_client_proto_init() }
func file_pkg_proto_client_proto_init() {
	if File_pkg_proto_client_proto != nil {
		return
	}
	file_pkg_proto_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientAuthorization); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientAuthorizationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlaveStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlavesStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlavesTop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_client_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_client_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_client_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientNewJobMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_client_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientJobSentResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_proto_client_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ClientRequest_NewJob)(nil),
		(*ClientRequest_JobList)(nil),
		(*ClientRequest_JobLog)(nil),
		(*ClientRequest_NodeList)(nil),
		(*ClientRequest_NodeTop)(nil),
	}
	file_pkg_proto_client_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*JobData_Pending)(nil),
		(*JobData_Running)(nil),
		(*JobData_ExitCode)(nil),
		(*JobData_RunError)(nil),
	}
	file_pkg_proto_client_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_pkg_proto_client_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*ClientJobSentResult_JobId)(nil),
		(*ClientJobSentResult_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_client_proto_goTypes,
		DependencyIndexes: file_pkg_proto_client_proto_depIdxs,
		MessageInfos:      file_pkg_proto_client_proto_msgTypes,
	}.Build()
	File_pkg_proto_client_proto = out.File
	file_pkg_proto_client_proto_rawDesc = nil
	file_pkg_proto_client_proto_goTypes = nil
	file_pkg_proto_client_proto_depIdxs = nil
}
