// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: pkg/proto/slave.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MasterToSlaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*MasterToSlaveRequest_GetStatus
	//	*MasterToSlaveRequest_NewJob
	//	*MasterToSlaveRequest_GetJobLogs
	Request isMasterToSlaveRequest_Request `protobuf_oneof:"request"`
}

func (x *MasterToSlaveRequest) Reset() {
	*x = MasterToSlaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_slave_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterToSlaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterToSlaveRequest) ProtoMessage() {}

func (x *MasterToSlaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_slave_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterToSlaveRequest.ProtoReflect.Descriptor instead.
func (*MasterToSlaveRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_slave_proto_rawDescGZIP(), []int{0}
}

func (m *MasterToSlaveRequest) GetRequest() isMasterToSlaveRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *MasterToSlaveRequest) GetGetStatus() *emptypb.Empty {
	if x, ok := x.GetRequest().(*MasterToSlaveRequest_GetStatus); ok {
		return x.GetStatus
	}
	return nil
}

func (x *MasterToSlaveRequest) GetNewJob() *SlaveJob {
	if x, ok := x.GetRequest().(*MasterToSlaveRequest_NewJob); ok {
		return x.NewJob
	}
	return nil
}

func (x *MasterToSlaveRequest) GetGetJobLogs() *GetJobLogsRequest {
	if x, ok := x.GetRequest().(*MasterToSlaveRequest_GetJobLogs); ok {
		return x.GetJobLogs
	}
	return nil
}

type isMasterToSlaveRequest_Request interface {
	isMasterToSlaveRequest_Request()
}

type MasterToSlaveRequest_GetStatus struct {
	GetStatus *emptypb.Empty `protobuf:"bytes,1,opt,name=getStatus,proto3,oneof"`
}

type MasterToSlaveRequest_NewJob struct {
	NewJob *SlaveJob `protobuf:"bytes,2,opt,name=newJob,proto3,oneof"`
}

type MasterToSlaveRequest_GetJobLogs struct {
	GetJobLogs *GetJobLogsRequest `protobuf:"bytes,3,opt,name=getJobLogs,proto3,oneof"`
}

func (*MasterToSlaveRequest_GetStatus) isMasterToSlaveRequest_Request() {}

func (*MasterToSlaveRequest_NewJob) isMasterToSlaveRequest_Request() {}

func (*MasterToSlaveRequest_GetJobLogs) isMasterToSlaveRequest_Request() {}

type SlaveToMasterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*SlaveToMasterRequest_Hello
	//	*SlaveToMasterRequest_JobFinished
	Request isSlaveToMasterRequest_Request `protobuf_oneof:"request"`
}

func (x *SlaveToMasterRequest) Reset() {
	*x = SlaveToMasterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_slave_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlaveToMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveToMasterRequest) ProtoMessage() {}

func (x *SlaveToMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_slave_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveToMasterRequest.ProtoReflect.Descriptor instead.
func (*SlaveToMasterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_slave_proto_rawDescGZIP(), []int{1}
}

func (m *SlaveToMasterRequest) GetRequest() isSlaveToMasterRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *SlaveToMasterRequest) GetHello() *SlaveHello {
	if x, ok := x.GetRequest().(*SlaveToMasterRequest_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *SlaveToMasterRequest) GetJobFinished() *JobFinishedResult {
	if x, ok := x.GetRequest().(*SlaveToMasterRequest_JobFinished); ok {
		return x.JobFinished
	}
	return nil
}

type isSlaveToMasterRequest_Request interface {
	isSlaveToMasterRequest_Request()
}

type SlaveToMasterRequest_Hello struct {
	Hello *SlaveHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type SlaveToMasterRequest_JobFinished struct {
	JobFinished *JobFinishedResult `protobuf:"bytes,2,opt,name=jobFinished,proto3,oneof"`
}

func (*SlaveToMasterRequest_Hello) isSlaveToMasterRequest_Request() {}

func (*SlaveToMasterRequest_JobFinished) isSlaveToMasterRequest_Request() {}

type SlaveHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// How should master connect to slave
	ConnectAddress string `protobuf:"bytes,1,opt,name=connect_address,json=connectAddress,proto3" json:"connect_address,omitempty"`
}

func (x *SlaveHello) Reset() {
	*x = SlaveHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_slave_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlaveHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveHello) ProtoMessage() {}

func (x *SlaveHello) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_slave_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveHello.ProtoReflect.Descriptor instead.
func (*SlaveHello) Descriptor() ([]byte, []int) {
	return file_pkg_proto_slave_proto_rawDescGZIP(), []int{2}
}

func (x *SlaveHello) GetConnectAddress() string {
	if x != nil {
		return x.ConnectAddress
	}
	return ""
}

// Message sent to slave after SlaveHello
type SlaveHelloMasterAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Slave ID
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SlaveHelloMasterAck) Reset() {
	*x = SlaveHelloMasterAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_slave_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlaveHelloMasterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveHelloMasterAck) ProtoMessage() {}

func (x *SlaveHelloMasterAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_slave_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveHelloMasterAck.ProtoReflect.Descriptor instead.
func (*SlaveHelloMasterAck) Descriptor() ([]byte, []int) {
	return file_pkg_proto_slave_proto_rawDescGZIP(), []int{3}
}

func (x *SlaveHelloMasterAck) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SlaveJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The command to run on node
	Cmd string `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	// The executable to send to node
	Program []byte `protobuf:"bytes,2,opt,name=program,proto3,oneof" json:"program,omitempty"`
}

func (x *SlaveJob) Reset() {
	*x = SlaveJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_slave_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlaveJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveJob) ProtoMessage() {}

func (x *SlaveJob) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_slave_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveJob.ProtoReflect.Descriptor instead.
func (*SlaveJob) Descriptor() ([]byte, []int) {
	return file_pkg_proto_slave_proto_rawDescGZIP(), []int{4}
}

func (x *SlaveJob) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *SlaveJob) GetProgram() []byte {
	if x != nil {
		return x.Program
	}
	return nil
}

type GetJobLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *GetJobLogsRequest) Reset() {
	*x = GetJobLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_slave_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobLogsRequest) ProtoMessage() {}

func (x *GetJobLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_slave_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobLogsRequest.ProtoReflect.Descriptor instead.
func (*GetJobLogsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_slave_proto_rawDescGZIP(), []int{5}
}

func (x *GetJobLogsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobCreatedResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *JobCreatedResult) Reset() {
	*x = JobCreatedResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_slave_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobCreatedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCreatedResult) ProtoMessage() {}

func (x *JobCreatedResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_slave_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCreatedResult.ProtoReflect.Descriptor instead.
func (*JobCreatedResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_slave_proto_rawDescGZIP(), []int{6}
}

func (x *JobCreatedResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobFinishedResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlaveId  uint32  `protobuf:"varint,1,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"`
	JobId    string  `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ExitCode *int32  `protobuf:"zigzag32,3,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	RunError *string `protobuf:"bytes,4,opt,name=run_error,json=runError,proto3,oneof" json:"run_error,omitempty"`
}

func (x *JobFinishedResult) Reset() {
	*x = JobFinishedResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_slave_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobFinishedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFinishedResult) ProtoMessage() {}

func (x *JobFinishedResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_slave_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFinishedResult.ProtoReflect.Descriptor instead.
func (*JobFinishedResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_slave_proto_rawDescGZIP(), []int{7}
}

func (x *JobFinishedResult) GetSlaveId() uint32 {
	if x != nil {
		return x.SlaveId
	}
	return 0
}

func (x *JobFinishedResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobFinishedResult) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *JobFinishedResult) GetRunError() string {
	if x != nil && x.RunError != nil {
		return *x.RunError
	}
	return ""
}

// Sent from master to slave after SlaveHello
type SlaveIDAssigned struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlaveId uint32 `protobuf:"varint,1,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"`
}

func (x *SlaveIDAssigned) Reset() {
	*x = SlaveIDAssigned{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_slave_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlaveIDAssigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveIDAssigned) ProtoMessage() {}

func (x *SlaveIDAssigned) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_slave_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveIDAssigned.ProtoReflect.Descriptor instead.
func (*SlaveIDAssigned) Descriptor() ([]byte, []int) {
	return file_pkg_proto_slave_proto_rawDescGZIP(), []int{8}
}

func (x *SlaveIDAssigned) GetSlaveId() uint32 {
	if x != nil {
		return x.SlaveId
	}
	return 0
}

var File_pkg_proto_slave_proto protoreflect.FileDescriptor

var file_pkg_proto_slave_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6c, 0x61, 0x76,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc0, 0x01, 0x0a, 0x14,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x54, 0x6f, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48,
	0x00, 0x52, 0x09, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a, 0x06,
	0x6e, 0x65, 0x77, 0x4a, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x4a, 0x6f, 0x62, 0x48, 0x00, 0x52,
	0x06, 0x6e, 0x65, 0x77, 0x4a, 0x6f, 0x62, 0x12, 0x3a, 0x0a, 0x0a, 0x67, 0x65, 0x74, 0x4a, 0x6f,
	0x62, 0x4c, 0x6f, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x67, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x4c,
	0x6f, 0x67, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8a,
	0x01, 0x0a, 0x14, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x54, 0x6f, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x6c, 0x61, 0x76, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x12, 0x3c, 0x0a, 0x0b, 0x6a, 0x6f, 0x62, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4a, 0x6f, 0x62, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x48, 0x00, 0x52, 0x0b, 0x6a, 0x6f, 0x62, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64,
	0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x0a, 0x53,
	0x6c, 0x61, 0x76, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x25, 0x0a, 0x13, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x41, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x08, 0x53, 0x6c, 0x61,
	0x76, 0x65, 0x4a, 0x6f, 0x62, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x1d, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x67,
	0x72, 0x61, 0x6d, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x22, 0x2a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x4c, 0x6f, 0x67, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x29,
	0x0a, 0x10, 0x4a, 0x6f, 0x62, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0xa5, 0x01, 0x0a, 0x11, 0x4a, 0x6f,
	0x62, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f,
	0x62, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x11, 0x48, 0x00, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x72, 0x75, 0x6e, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x08, 0x72, 0x75, 0x6e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x72, 0x75, 0x6e, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x2c, 0x0a, 0x0f, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x49, 0x44, 0x41, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x49, 0x64, 0x42,
	0x0f, 0x5a, 0x0d, 0x57, 0x4c, 0x46, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_slave_proto_rawDescOnce sync.Once
	file_pkg_proto_slave_proto_rawDescData = file_pkg_proto_slave_proto_rawDesc
)

func file_pkg_proto_slave_proto_rawDescGZIP() []byte {
	file_pkg_proto_slave_proto_rawDescOnce.Do(func() {
		file_pkg_proto_slave_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_slave_proto_rawDescData)
	})
	return file_pkg_proto_slave_proto_rawDescData
}

var file_pkg_proto_slave_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_slave_proto_goTypes = []interface{}{
	(*MasterToSlaveRequest)(nil), // 0: proto.MasterToSlaveRequest
	(*SlaveToMasterRequest)(nil), // 1: proto.SlaveToMasterRequest
	(*SlaveHello)(nil),           // 2: proto.SlaveHello
	(*SlaveHelloMasterAck)(nil),  // 3: proto.SlaveHelloMasterAck
	(*SlaveJob)(nil),             // 4: proto.SlaveJob
	(*GetJobLogsRequest)(nil),    // 5: proto.GetJobLogsRequest
	(*JobCreatedResult)(nil),     // 6: proto.JobCreatedResult
	(*JobFinishedResult)(nil),    // 7: proto.JobFinishedResult
	(*SlaveIDAssigned)(nil),      // 8: proto.SlaveIDAssigned
	(*emptypb.Empty)(nil),        // 9: google.protobuf.Empty
}
var file_pkg_proto_slave_proto_depIdxs = []int32{
	9, // 0: proto.MasterToSlaveRequest.getStatus:type_name -> google.protobuf.Empty
	4, // 1: proto.MasterToSlaveRequest.newJob:type_name -> proto.SlaveJob
	5, // 2: proto.MasterToSlaveRequest.getJobLogs:type_name -> proto.GetJobLogsRequest
	2, // 3: proto.SlaveToMasterRequest.hello:type_name -> proto.SlaveHello
	7, // 4: proto.SlaveToMasterRequest.jobFinished:type_name -> proto.JobFinishedResult
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_proto_slave_proto_init() }
func file_pkg_proto_slave_proto_init() {
	if File_pkg_proto_slave_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_slave_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterToSlaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_slave_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlaveToMasterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_slave_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlaveHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_slave_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlaveHelloMasterAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_slave_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlaveJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_slave_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_slave_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobCreatedResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_slave_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobFinishedResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_slave_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlaveIDAssigned); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_proto_slave_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*MasterToSlaveRequest_GetStatus)(nil),
		(*MasterToSlaveRequest_NewJob)(nil),
		(*MasterToSlaveRequest_GetJobLogs)(nil),
	}
	file_pkg_proto_slave_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SlaveToMasterRequest_Hello)(nil),
		(*SlaveToMasterRequest_JobFinished)(nil),
	}
	file_pkg_proto_slave_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_pkg_proto_slave_proto_msgTypes[7].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_slave_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_slave_proto_goTypes,
		DependencyIndexes: file_pkg_proto_slave_proto_depIdxs,
		MessageInfos:      file_pkg_proto_slave_proto_msgTypes,
	}.Build()
	File_pkg_proto_slave_proto = out.File
	file_pkg_proto_slave_proto_rawDesc = nil
	file_pkg_proto_slave_proto_goTypes = nil
	file_pkg_proto_slave_proto_depIdxs = nil
}
